# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!

def shared_pods
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'WKCFansyPhotoLiveView'

end

abstract_target 'pod-libs' do
  shared_pods
  target 'Demo'
end
